#!/usr/bin/env bash
# generate_curl_commands.sh — Generate a ready-to-run bash script of curl commands
#                             to configure Cloudflare Magic WAN IPsec tunnels on
#                             Aruba EdgeConnect appliances.
#
# Reads tunnel data from 'terraform output' in the parent directory and produces
# a self-contained script (apply-tunnels.sh by default) containing one section
# per appliance: login → POST tunnels → logout.
#
# The PSK is read from terraform output and embedded in the generated script.
# Treat the generated file as a secret.
#
# Usage:
#   bash aruba/generate_curl_commands.sh [--output FILE] [--verify-ssl]
#   bash aruba/generate_curl_commands.sh --output -    # print to stdout
#
# Requirements: terraform in PATH, jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$SCRIPT_DIR/apply-tunnels.sh"
CURL_VERIFY=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --output)     OUTPUT="$2"; shift 2 ;;
    --verify-ssl) CURL_VERIFY=true; shift ;;
    *) echo "Usage: $(basename "$0") [--output FILE] [--verify-ssl]"; exit 1 ;;
  esac
done

info()  { echo "INFO  $*" >&2; }
error() { echo "ERROR $*" >&2; exit 1; }

for cmd in terraform jq; do
  command -v "$cmd" &>/dev/null || error "$cmd not found in PATH"
done

# ---------------------------------------------------------------------------
# Read terraform outputs
# ---------------------------------------------------------------------------
info "Reading terraform outputs from $TF_DIR ..."

pushd "$TF_DIR" > /dev/null
TUNNEL_JSON=$(terraform output -json tunnel_details 2>/dev/null) \
  || error "Could not read tunnel_details. Run 'terraform apply' first."
PSK=$(terraform output -raw tunnel_psk 2>/dev/null) \
  || error "Could not read tunnel_psk. Run 'terraform apply' first."
popd > /dev/null

TUNNEL_COUNT=$(echo "$TUNNEL_JSON" | jq 'keys | length')
info "Found $TUNNEL_COUNT tunnel(s)"

# ---------------------------------------------------------------------------
# curl TLS flag
# ---------------------------------------------------------------------------
K=""
$CURL_VERIFY || K="-k"

# ---------------------------------------------------------------------------
# Helper: build a fully static, compact tunnel POST payload with PSK embedded
# ---------------------------------------------------------------------------
build_payload() {
  local t="$1"
  echo "$t" | jq -c --arg psk "$PSK" '
    {
      (.tunnel_name): {
        admin:            "up",
        alias:            .tunnel_name,
        auto_mtu:         true,
        gms_marked:       false,
        ipsec_enable:     true,
        ipsec_arc_window: "disable",
        presharedkey:     $psk,
        mode:             "ipsec_ip",
        nat_mode:         "none",
        peername:         "Cloudflare_IPSec",
        source:           (if (.customer_endpoint // "") == "" then "0.0.0.0" else .customer_endpoint end),
        destination:      .cloudflare_endpoint,
        max_bw_auto:      true,
        local_vrf:        0,
        ipsec: {
          ike_version:   2,
          ike_ealg:      "aes256",
          ike_aalg:      "sha256",
          ike_prf:       "auto",
          dhgroup:       "14",
          pfs:           true,
          pfsgroup:      "14",
          ipsec_suite_b: "none",
          id_type:       "ufqdn",
          ike_id_local:  .fqdn_id,
          ike_id_remote: .cloudflare_endpoint,
          exchange_mode: "aggressive",
          mode:          "tunnel",
          esn:           false,
          dpd_delay:     0,
          dpd_retry:     3,
          ike_lifetime:  0,
          lifetime:      240,
          lifebytes:     0,
          security: {
            ah:  { algorithm: "sha256" },
            esp: { algorithm: "aes256" }
          }
        }
      }
    }
  '
}

# ---------------------------------------------------------------------------
# Collect unique appliances sorted by ec_hostname
# ---------------------------------------------------------------------------
APPLIANCES=()
while IFS= read -r host; do
  APPLIANCES+=("$host")
done < <(echo "$TUNNEL_JSON" | jq -r '[.[].ec_hostname] | unique | sort[]')

info "Generating curl commands for ${#APPLIANCES[@]} appliance(s)..."

# ---------------------------------------------------------------------------
# Accumulate the generated script into a temp file, then write to OUTPUT
# ---------------------------------------------------------------------------
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# ---- Script header (written verbatim) ----
cat >> "$TMP" <<'EOF'
#!/usr/bin/env bash
# apply-tunnels.sh — Auto-generated by generate_curl_commands.sh
#
# Configures Cloudflare Magic WAN IPsec tunnels on Aruba EdgeConnect appliances
# via the ECOS REST API.
#
# Usage:
#   bash apply-tunnels.sh [--username admin] [--password PASS] [--sites HOST1,HOST2]
#
# --sites filters by ec_hostname (comma-separated). Default: all appliances.
# The IPsec PSK is embedded in this script — treat it as a secret.

set -euo pipefail

USERNAME="admin"
PASSWORD=""
SITES_FILTER=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --username) USERNAME="$2"; shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    --sites)    SITES_FILTER="$2"; shift 2 ;;
    *) echo "Usage: $(basename "$0") [--username USER] [--password PASS] [--sites HOST1,HOST2]"
       exit 1 ;;
  esac
done

[[ -z "$PASSWORD" ]] && {
  read -rsp "EdgeConnect password for $USERNAME: " PASSWORD
  echo >&2
}

_info()  { echo "INFO  $*"; }
_warn()  { echo "WARN  $*" >&2; }
_error() { echo "ERROR $*" >&2; }

_site_selected() {
  local host="$1"
  [[ -z "$SITES_FILTER" ]] && return 0
  local IFS=',' f
  for f in $SITES_FILTER; do
    [[ "${f// /}" == "$host" ]] && return 0
  done
  return 1
}

ERRORS=0
EOF

# ---- Embed PSK ----
ESCAPED_PSK="${PSK//\'/\'\\\'\'}"
printf "\n# IPsec PSK — embedded at generation time\n"        >> "$TMP"
printf "_PSK='%s'\n"  "$ESCAPED_PSK"                          >> "$TMP"

# ---- Per-appliance sections ----
for ec_host in "${APPLIANCES[@]}"; do
  SITE_TUNNELS=$(echo "$TUNNEL_JSON" | jq -c --arg h "$ec_host" '
    [to_entries[] | select(.value.ec_hostname == $h) | .value]
    | sort_by(.tunnel_name)
  ')
  SITE_NAME=$(echo "$SITE_TUNNELS" | jq -r '.[0].site_name')

  {
    printf '\n'
    printf '# ===========================================================================\n'
    printf '# Site: %s  |  Appliance: %s\n' "$SITE_NAME" "$ec_host"
    printf '# ===========================================================================\n'
    printf 'if _site_selected "%s"; then\n'                         "$ec_host"
    printf '  _info ""\n'
    printf '  _info "--- Site: %s  appliance: %s ---"\n'            "$SITE_NAME" "$ec_host"
    printf '  _HDR=$(mktemp)\n'
    printf '  _http=$(curl -s %s -D "$_HDR" -o /dev/null -w "%%{http_code}" \\\n'  "$K"
    printf '    -X POST "https://%s/rest/json/login" \\\n'              "$ec_host"
    printf '    -H "Content-Type: application/json" \\\n'
    printf '    -d "{\"user\":\"$USERNAME\",\"password\":\"$PASSWORD\"}")\n'
    printf '  _auth=$(grep -i "^Set-Cookie:" "$_HDR" | grep -o "vxoaSessionID=[^;]*" || echo "")\n'
    printf '  rm -f "$_HDR"\n'
    printf '  if [[ "$_http" != "200" && "$_http" != "204" ]] || [[ -z "$_auth" ]]; then\n'
    printf '    _error "Login to %s failed (HTTP $_http) — skipping"\n' "$ec_host"
    printf '    ERRORS=$((ERRORS+1))\n'
    printf '  else\n'
    printf '    _info "  Logged in OK"\n'
  } >> "$TMP"

  while IFS= read -r t; do
    TNAME=$(echo "$t" | jq -r '.tunnel_name')
    CF_EP=$(echo "$t" | jq -r '.cloudflare_endpoint')
    SRC=$(echo "$t"   | jq -r '.customer_endpoint // "(dynamic)"')
    PAYLOAD=$(build_payload "$t")
    # Escape single quotes inside the JSON payload for shell embedding
    EPAYLOAD="${PAYLOAD//\'/\'\\\'\'}"

    {
      printf '\n'
      printf '    # %s  remote=%s  local=%s\n'                          "$TNAME" "$CF_EP" "$SRC"
      printf '    _info "  Creating %s..."\n'                           "$TNAME"
      printf '    _http=$(curl -s %s -o /tmp/_ec_$$.json -w "%%{http_code}" \\\n'  "$K"
      printf '      -H "Cookie: $_auth" -X POST "https://%s/rest/json/thirdPartyTunnels/config" \\\n'  "$ec_host"
      printf "      -H 'Content-Type: application/json' -d '%s')\n"    "$EPAYLOAD"
      printf '    if [[ "$_http" == "200" || "$_http" == "201" || "$_http" == "204" ]]; then\n'
      printf '      _info "    OK (HTTP $_http)"\n'
      printf '    else\n'
      printf '      _warn "    FAILED (HTTP $_http)"; cat /tmp/_ec_$$.json >&2 2>/dev/null || true\n'
      printf '      ERRORS=$((ERRORS+1))\n'
      printf '    fi\n'
      printf '    rm -f /tmp/_ec_$$.json\n'
    } >> "$TMP"
  done < <(echo "$SITE_TUNNELS" | jq -c '.[]')

  {
    printf '\n'
    printf '    curl -s %s -H "Cookie: $_auth" -X DELETE "https://%s/rest/json/login" -o /dev/null || true\n'  "$K" "$ec_host"
    printf '    _info "  Logged out"\n'
    printf '  fi\n'
    printf 'else\n'
    printf '  _info "Skipping %s (not in --sites filter)"\n'  "$ec_host"
    printf 'fi\n'
  } >> "$TMP"

done  # per-appliance

# ---- Footer ----
cat >> "$TMP" <<'EOF'

if [[ $ERRORS -eq 0 ]]; then
  echo "INFO  All tunnels configured successfully."
else
  echo "ERROR Completed with $ERRORS error(s)." >&2
  exit 1
fi
EOF

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
if [[ "$OUTPUT" == "-" ]]; then
  cat "$TMP"
else
  cp "$TMP" "$OUTPUT"
  chmod +x "$OUTPUT"
  info ""
  info "Written to: $OUTPUT"
  info ""
  info "Next steps:"
  info "  1. Review $OUTPUT"
  info "  2. bash $OUTPUT --username admin"
  info "     (optionally: --sites 192.168.100.10,192.168.100.11)"
  info ""
  info "NOTE: The PSK is embedded in $OUTPUT — treat it as a secret."
fi
